generate_joke_task:
  description: >
    Generate 10 Rajni Kanth jokes on demand.
  expected_output: >
    A list of 10 Rajni Kanth jokes.
  agent: rajni_kanth_joke_generator

pick_joke_task:
  description: >
    Pick the best Rajni Kanth joke from a collection of 10 jokes.
  expected_output: >
    The best joke from the collection.
  agent: rajni_kanth_joke_picker
